### ISSUE TITLE
refuse to push new branches

### ISSUE THREAD

**Issue by SuYe99** [GERSL/pycold#13]
@Erotemic I am trying to push a new feature branch (I am currently working on), but received an reject:

> [remote rejected] devel -> devel-suy (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/tests.yml` without `workflow` scope) error: failed to push some refs to 'https://github.com/GERSL/pycold.git'

It looks like being blocked by certain rules from your added workflow. Do you know how to bypass it?

Su

**Comment by Erotemic** [comment]
That's very strange. I've never seen anything like that.

When you run `git branch` on your local machine, do you see `devel-suy` highlighted? Or is it `devel`, and and you are using a command like `git push origin devel:devel-suv`?

I don't think the workflow is adding rules, but if it is we should address that. I'll try to run some tests on my end too.

**Comment by Erotemic** [comment]
Hmm, I tried both methods where I made a dummy change on devel directly and did `git push origin devel:test-change` (i.e. so the change was on my local devel but I pushed it to origin as if it was a new branch "test-change"), and that worked.

I also did `git checkout -b test2` to make a new branch of of devel, made a change and did `git push origin` and that pushed my branch test2 to origin as well.

So neither method gave me issues. 

This is a long shot, but perhaps your changes aren't compatible with the latest devel? Maybe try to `git fetch origin` and then `git rebase -i origin/devel` to ensure your change are rebased on top of the latest "devel" branch? I'm still pretty unsure what the issue is, so I'm not sure if any of these suggestions will work. 

EDIT: What would help me understand better is: 

1. What is the result of `git status`?
2. What is the result of `git branch`?
3. What command were you running when you got the error?

**Comment by SuYe99** [comment]
Hi Jon,

The problem was solved after I rebased my new changes. Thank you for this suggestion. I will rebase my branch once you have updates on devel. It is good to know this tip. 

I will continue to work on my branch, which also includes some critical changes to enable processing for Landsat ARD C2. @twin22jw you can pull my branch 'devel-suy' using 'git pull origin devel-suy:devel'; the new prepare_ard.py (the same as I sent you on Friday in email) should be helpful to your current ARD C2 tests. 


Su
