### ISSUE TITLE
Allowing different combinations of indices/bands as inputs

### ISSUE THREAD

**Issue by SuYe99** [GERSL/pycold#34]
I received a request from a user for upgrading cold_detect to accept user-defined indices or band combination. So far, the technical problem is mainly at its causing C struct 'Output_t' to be variable by the input band number. But we may have solutions in [https://github.com/GERSL/pycold/blob/devel/src/python/pycold/colds.py](colds.py) to 'customize' a default-lengthy 'Output_t' in python.
My current plan is to create a new function called 'cold_detect_super(green, swir1, B1,B2,B3,B4,B5,B6,B7...)'.  We still need green and swir1 bands anyway to do TMask.
@twin22jw does the WATCH project need this functionality?

**Comment by Erotemic** [comment]
It wouldn't hurt. One of the things WATCH has the capability of is to perform computation on customized band combinations using the [sensor/channel spec](https://gitlab.kitware.com/computer-vision/delayed_image).

Could you rework inputs/outputs such that instead of accepting a single array for each band individually you accept a multi dimensional array containing all bands together as well as a string array indicating the label of each band? On the Python side this would be an ndarray with shape NxB containing the data and a string array of length B containing the band names, where N is the number of pixels and B is the number of bands. That should be managable in C and it would simplify the call signatures, although you will have to define expected band names if you treat them differently in the algorithm itself.

**Comment by SuYe99** [comment]
Finally finish this functinality. Now the users can use the function 'cold_detect_flex' to input any band combination for cold processing.
